# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import appstract_pb2 as appstract__pb2


class ClusteringStub(object):
    """----------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateClustering = channel.unary_unary(
                '/proto_appstract.Clustering/CreateClustering',
                request_serializer=appstract__pb2.CreateClusteringRequest.SerializeToString,
                response_deserializer=appstract__pb2.ClusteringResponse.FromString,
                )
        self.GetClusterers = channel.unary_unary(
                '/proto_appstract.Clustering/GetClusterers',
                request_serializer=appstract__pb2.Empty.SerializeToString,
                response_deserializer=appstract__pb2.ClusterersReply.FromString,
                )


class ClusteringServicer(object):
    """----------------------------------------------------------------------------
    """

    def CreateClustering(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClusterers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClusteringServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateClustering': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateClustering,
                    request_deserializer=appstract__pb2.CreateClusteringRequest.FromString,
                    response_serializer=appstract__pb2.ClusteringResponse.SerializeToString,
            ),
            'GetClusterers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusterers,
                    request_deserializer=appstract__pb2.Empty.FromString,
                    response_serializer=appstract__pb2.ClusterersReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto_appstract.Clustering', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Clustering(object):
    """----------------------------------------------------------------------------
    """

    @staticmethod
    def CreateClustering(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto_appstract.Clustering/CreateClustering',
            appstract__pb2.CreateClusteringRequest.SerializeToString,
            appstract__pb2.ClusteringResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetClusterers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto_appstract.Clustering/GetClusterers',
            appstract__pb2.Empty.SerializeToString,
            appstract__pb2.ClusterersReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)